### ISSUE TITLE
flushed output consists of NaN

### ISSUE THREAD

**Issue by chaindl** [AxiSEMunity/AxiSEM3D#24]
Hi Kuangdai,

I had a long run terminate prematurely and the flush option was set to true for the element outputs. But the .nc file is completely filled with NaNs - even the coordinates. It definitely should have flushed several times based on the interval I set.

**Comment by kuangdai** [comment]
HI Claudia, I cannot reproduce this issue. It is probably a system-based issue. Closing this for now..
