### ISSUE TITLE
off-axis source location issue

### ISSUE THREAD

**Issue by chaindl** [AxiSEMunity/AxiSEM3D#25]
Hi!

I've come across an issue when it comes to locating the sources in the azimuth. It seems that when using the distance_azimuth input for an off axis source, the azimuth is measured clockwise which is against the standard convention. Meanwhile, models with distance_azimuth inputs are read in normally (as in the azimuth is interpreted as counter-clockwise). 

Here is an example of a surface wavefield near the start of a simulation with a falsely placed source (the cross is where I would expect it to be):

![source_location_issue](https://user-images.githubusercontent.com/35463653/142272784-a959e353-56f5-45e9-bbee-ede9dd753cfc.png)

**Comment by kuangdai** [comment]
Hi Claudia, please upload the input folder.

**Comment by chaindl** [comment]
[input.zip](https://github.com/kuangdai/AxiSEM-3D/files/7557896/input.zip)

Thanks!

**Comment by kuangdai** [comment]
On line 52 of Mechanism.cpp

```c++
const numerical::ComplexD i_phi(0., phi);
```

Can you try changing it to 

```c++
const numerical::ComplexD i_phi(0., -phi);
```

and see if the problem can be solved?

From the equations, here could be a minus sign.

**Comment by chaindl** [comment]
Yes, that looks much better.

**Comment by chaindl** [comment]
![source_location_issue_fixed](https://user-images.githubusercontent.com/35463653/142285672-58047612-f28f-4d9c-aea7-82d1a2b251c4.png)
