### ISSUE TITLE
What are the other formats for .bm files?

### ISSUE THREAD

**Issue by axelwang** [AxiSEMunity/AxiSEM3D#30]
Hey, 
  I looked at some .bm files used when generating a 2D mesh. I noticed that many of them, say prem_iso.bm and prem_ani.bm have a format that is very different from what's described in the Mesher section about background models. I am wondering how should I interpret these? In particular, I am baffled by the material properties section.

  Thanks!

**Comment by axelwang** [comment]
Ah the numbers following the first column are the coefficients of polynomials for the respective Earth models. For PREM, they can be found here: [https://doi.org/10.1016/0031-9201(81)90046-7](https://doi-org.stanford.idm.oclc.org/10.1016/0031-9201(81)90046-7)! Closing this issue now but hopefully this can be helpful for someone else in the future!

**Comment by zhouytl** [comment]
Hi, thank you for sharing it. I wonder where you found the prem_iso.bm and prem_ani.bm files? thanks!

**Comment by williameaton** [comment]
The bm file can define the model in two ways, either by specifying the layers or polynomials, determined by the line 

```
MODEL_TYPE          poly
```
which can be 'poly' or 'layer'.  As Axel mentioned, some models such as PREM are defined as piecewise-continuous polynomials so you can choose whichever method is easiest for your model. 

You can find a couple of examples of different .bm files included in the [Salvus Mesher Lite](https://gitlab.com/Salvus/SalvusMeshLite/-/tree/master/salvus_mesh_lite/data?ref_type=heads) package within the ```data``` directory. Hope that helps!

**Comment by zhouytl** [comment]
Thank you very much!!
