### ISSUE TITLE
Showing physical 3D models "as seen by AxiSEM3D"

### ISSUE THREAD

**Issue by axelwang** [AxiSEMunity/AxiSEM3D#32]
This is related to #31 , and again I am only considering a 2D cross-section of a 3D model.  The goal here is to plot a 2D cross section showing the actual properties (e.g. shear wave speed). The motivation is to show the exact property distributions on the same points where the wavefield is output. 

Basically, this is the same as #31 , but instead of plotting the wavefields on each GLL points in the physical domain, here I would like to plot, say Vs, on these GLL points. 

I think there are 3 kinds of models relevant to AxiSEM3D:

1. The input models. This is something like crust1.0. These generally are somewhat different from the model actually used for computation, due to interpolation (in case the computational points are denser than the grids for the input models) or downsampling (in case the computational points are sparser). 
2. Particle-relabelled models. These are made from the input models and are regular and axisymmetric, so these are the models *as seen by AxiSEM3D* and are used for the actual computation. However, these are not intuitive at all to show for research purposes, i.e. the visualization will look nothing like e.g. crust 1.0 or any tomography model. 
3. Inverse particle-relabelled models. These are never made or used by AxiSEM3D. This is a conceptual idea and is what I think should be considered for adding. This basically just inverse transforms the model actually used for computation but also put it into a format that people can easily understand, i.e. these will look like crust 1.0 or whatever the actual input models are. 

I think the issue here, like in #31 , is to apply the inverse particle-relabelling transformation to more quantities that are not just the wavefield.

**Comment by kuangdai** [comment]
1. A module for model visualization has not been developed in this code, unfortunately. Unless new development force is employed, I am afraid this will remain undone.

2. The relabelled modes are gemetrically axisymmetric but have complicated elastic parameters. The Cijkl in the most general anisotroy has 21 independent parameters, which is already difficult to visualize, while a relabelled model has 35.

3. The PRT is invertable. But I think the inverse model is just the input model (undulated one), isn't it?

**Comment by axelwang** [comment]
> The PRT is invertable. But I think the inverse model is just the input model (undulated one), isn't it?
I think this is not always the case because an input model could be too fine for a mesh, i.e. when a mesh samples the model inadequately. In this case, the inverse transformed axisymmetric model would not recover the original input model. My whole issue here again is to figure out a way to output something exactly used by the code, but for the model in AxiSEM3D that is not useful because the model actually used is not physical, and that's why I proposed adding the inverse transform which would give a physical version of "model actually used". 

I give my scenario a bit more thought and realized that this actually won't be a big issue for me, because my mesh grid will always be much denser than the model grid, so simply plotting the model should be good enough for me.
