### ISSUE TITLE
Meaning of "undulated_geometry" option for station output

### ISSUE THREAD

**Issue by axelwang** [AxiSEMunity/AxiSEM3D#33]
In the WiKi, under Station output, we have
`undulated_geometry`: _If set to "true", the vertical coordinate of stations (either "DEPTH" or "RADIUS") will be determined with respect to the undulated geometry, otherwise with respect to the reference geometry._

What does this mean? Here is an example of my confusion: 

Say we have a station with depth 0 (on earth's surface) in the text file containing a list of stations. If `undulated_geometry` is false,  then this station is at the top of the reference model (depth 0) and is actually at the earth's surface. If `undulated_geometry` is true,  and let's say at the horizontal coordinates of this location there is an upward undulation, then does this station will now be inside the earth (maintaining depth 0) or will its depth be changed according to the upward undulation such that this station is still at the surface? If it's the latter case, then the changed station locations would actually track the undulation of a layer. 

I couldn't easily check this because the station output files do not contain the station locations after turning `undulated_geometry` on or off, in neither output formats (ASCII or NetCDF). 

It seems like #18 offers some hints on how to get the GLL points in the undulated geometry and thus plotting the undistorted wave field. However, it's clear one would need to dig much deeper into the code to do this.

**Comment by kuangdai** [comment]
For a station with depth=24.4 km (Moho depth in PREM) 
* if `undulated_geometry=false`, this station is always located on the Moho, because this 24.4km is measured on PREM
* if `undulation_geometry=true`, this station will be in the mantle if it is in the ocean, and will be in the crust if it is on a continent. This is because, when `undulation_geometry=true`, this 24.4km is measured on Crust 1.  

For a station with depth=0, it is *always* located on the surface regardless of `undulated_geometry `, because 0 is 0 no matter how you measure it.

**Comment by axelwang** [comment]
Hey Kuangdai, thanks for these clarifications. 

With your Moho example, when `undulated_geometry=false`, you mention that this station is always located on the Moho. However, in a 3D model where Moho deviates from 24.4 km, does `undulated_geometry=false` makes the station to actually change depth so that it tracks the Moho? If this is true, these changed vertical coordinates are not being output?

Similarly, when `undulated_geometry=true`, you mention that 24.4 km is measured on a 3D model, which means that 24.4 km will be the actual vertical coordinate for this station, and no further adjustment will be made?
