### ISSUE TITLE
Station NetCDF output should include station coordinates

### ISSUE THREAD

**Issue by jbmuir** [AxiSEMunity/AxiSEM3D#36]
The NetCDF output for stations currently only includes the station codes and channel names; including the locations of the stations in the output would increase user friendliness (as you wouldn't have to write a script to combine them back up again in post-processing) at presumably relatively minor developer cost.

**Comment by kuangdai** [comment]
Thanks for the suggestion. I tried a bit jut now. This is not as easy as it looks. 

For station-wise output, we support a varity of input coordinate systems and output formats, which are handled by three base classes in the most logical way:

`preloop/output/StationOuput`: handling input (horizontal: lat/long, dist/azimuth, x/y; vertical: depth, radius; so there are 6 combinations)
`core/output/station-wise/station/Station`: recording wavefields during timeloop (it stores station location as which element it belongs to and the interpolation weights of each GLL in that element, as calculated from `StationOutput`)
`core/output/station-wise/io/StationIO`: handle different file formats (ascii/netcdf) and storage arrangements (station-wise or channel-wise) 

In an object-oriented framework, a seemingly simple addition such as this one can invovle lots of coding if we want to do it in a consistent manner for all the combinations. Even if we say, we only want this for station-wise netcdf, we need to change all the classes invovled.
