### ISSUE TITLE
Gradient of displacement field in fluid regions

### ISSUE THREAD

**Issue by Adrian-Mag** [AxiSEMunity/AxiSEM3D#42]
Would it be possible/feasible to add the option of outputting the gradient of displacement for fluid regions (for element output at least)? The displacement gradient is needed for computing geometric sensitivity kernels at the CMB. While this could be approximated using the displacement output from the element output, it just would not be as accurate without using the proper xi-eta transformation (correct me if I'm wrong).

**Comment by kuangdai** [comment]
Gradient of displacement is strain. In fluid, strain is 

$$
\epsilon_{ij}=\frac{\Delta}{3}\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix},
$$

where $\Delta$ is dilatation or change of volume, which is computed by

$$\Delta= P / K,$$

where $K$ is bulk modules and $P$ is pressure. $P$ is an output of AxiSEM3D and $K=\rho * v_p^2$. This is why we don't need to output stress and strain in fluid.
